### ISSUE TITLE
Support typescript/ type annotations

### ISSUE THREAD

**Issue by sheen4n** [samliew/singapore-nric#5]
Hi @samliew , is it possible for us to raise a PR from a fork to provide typing annotations or convert the project to typescript, so that users of the npm library can use this package seamlessly in their .ts projects? :) 

I don't mind contributing to this as we need that feature now. (Right now the workaround is we included a .d.ts file to manually provide types)

**Comment by samliew** [comment]
You should be able to raise a PR in the original repo where you forked from

**Comment by sheen4n** [comment]
Hi Sam, I have made a pull request regarding this feature, do help to take a look :) https://github.com/samliew/singapore-nric/pull/6

**Comment by samliew** [comment]
I've reviewed and merged to main. Also, I have given you npm access to publish a new version if there are breaking changes that need addressed (especially if I am no longer available in future for some reason).

**Comment by sheen4n** [comment]
Thank you @samliew , sure!
